import type { LightNovel } from '../types/ln';

export const POPULAR_KOREAN_NOVELS: LightNovel[] = [
    {
        id: 'nb:solo-leveling',
        mal_id: 'nb:solo-leveling',
        title: 'Solo Leveling',
        title_english: 'Solo Leveling',
        title_romaji: 'Na Honjaman Level Up',
        title_native: '나 혼자만 레벨업',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/solo-leveling.jpg',
                large_image_url: 'https://novel-bin.com/files/image/solo-leveling.jpg',
            },
        },
        score: 9.2,
        rank: 1,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:solo-leveling',
        synopsis: '10 years ago, after the Gate that connected the real world with the monster world opened, some ordinary people received awakening powers. Sung Jin-Woo, known as the Weakest Hunter of All Mankind, finds a mysterious Double Dungeon and awakens a unique quest log system.',
        author: 'Chugong',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Fantasy' },
            { mal_id: 3, name: 'System' },
            { mal_id: 4, name: 'Supernatural' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/solo-leveling.jpg',
    },
    {
        id: 'nb:omniscient-reader',
        mal_id: 'nb:omniscient-reader',
        title: "Omniscient Reader's Viewpoint",
        title_english: "Omniscient Reader's Viewpoint",
        title_romaji: 'Jeonjijeok Dokja Sijeom',
        title_native: '전지적 독자 시점',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/omniscient-reader.jpg',
                large_image_url: 'https://novel-bin.com/files/image/omniscient-reader.jpg',
            },
        },
        score: 9.4,
        rank: 2,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:omniscient-reader',
        synopsis: "'This is a development that I know.' The apocalyptic web novel 'Three Ways to Survive the Apocalypse' that Dokja Kim read for over ten years has suddenly become reality, and he is the sole person who knows the ending.",
        author: 'Sing Shong',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Adventure' },
            { mal_id: 3, name: 'Apocalypse' },
            { mal_id: 4, name: 'Psychological' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/omniscient-reader.jpg',
    },
    {
        id: 'nb:the-beginning-after-the-end',
        mal_id: 'nb:the-beginning-after-the-end',
        title: 'The Beginning After the End',
        title_english: 'The Beginning After the End',
        title_romaji: 'The Beginning After the End',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/the-beginning-after-the-end.jpg',
                large_image_url: 'https://novel-bin.com/files/image/the-beginning-after-the-end.jpg',
            },
        },
        score: 9.1,
        rank: 3,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:the-beginning-after-the-end',
        synopsis: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Reincarnated into a new world filled with magic and monsters, the king has a second chance to relive his life.',
        author: 'TurtleMe',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Fantasy' },
            { mal_id: 3, name: 'Isekai' },
            { mal_id: 4, name: 'Magic' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/the-beginning-after-the-end.jpg',
    },
    {
        id: 'nb:second-life-ranker',
        mal_id: 'nb:second-life-ranker',
        title: 'Second Life Ranker',
        title_english: 'Second Life Ranker',
        title_romaji: 'Du Beon Saneun Ranker',
        title_native: '두 번 사는 랭커',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/second-life-ranker.jpg',
                large_image_url: 'https://novel-bin.com/files/image/second-life-ranker.jpg',
            },
        },
        score: 8.8,
        rank: 4,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:second-life-ranker',
        synopsis: 'Yeon-woo had a twin brother who disappeared five years ago. One day, a pocket watch left by his brother returned to his possession, containing a hidden diary recording the betrayal he faced in the Obelisk Tower of the Sun God.',
        author: 'Nong Nong / Sadoyeon',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Tower' },
            { mal_id: 3, name: 'Revenge' },
            { mal_id: 4, name: 'Fantasy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/second-life-ranker.jpg',
    },
    {
        id: 'nb:nano-machine',
        mal_id: 'nb:nano-machine',
        title: 'Nano Machine',
        title_english: 'Nano Machine',
        title_romaji: 'Nano Masin',
        title_native: '나노 마신',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/nano-machine.jpg',
                large_image_url: 'https://novel-bin.com/files/image/nano-machine.jpg',
            },
        },
        score: 8.9,
        rank: 5,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:nano-machine',
        synopsis: 'Cheon Yeo-Woon, the unranked prince of the Demonic Cult, lives a perilous life surrounded by hostile clan members. When an unexpected descendant from the future injects him with cutting-edge Nano Machines, his destiny is rewritten.',
        author: 'Hanjung Wookhyup',
        genres: [
            { mal_id: 1, name: 'Murim' },
            { mal_id: 2, name: 'Martial Arts' },
            { mal_id: 3, name: 'Sci-Fi' },
            { mal_id: 4, name: 'Action' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/nano-machine.jpg',
    },
    {
        id: 'nb:the-s-classes-that-i-raised',
        mal_id: 'nb:the-s-classes-that-i-raised',
        title: 'The S-Classes That I Raised',
        title_english: 'The S-Classes That I Raised',
        title_romaji: 'Naega Kiun S-geupdeul',
        title_native: '내가 키운 S급들',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/the-s-classes-that-i-raised.jpg',
                large_image_url: 'https://novel-bin.com/files/image/the-s-classes-that-i-raised.jpg',
            },
        },
        score: 8.7,
        rank: 6,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:the-s-classes-that-i-raised',
        synopsis: 'An F-rank hunter, Han Yu-jin, raises an extraordinary S-rank little brother who sacrificed his life for him. Rewinding time after making a wish with a magic stone, he receives the title Perfect Caretaker and begins rearing S-rank hunters.',
        author: 'Geunseo',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Fantasy' },
            { mal_id: 3, name: 'Hunter' },
            { mal_id: 4, name: 'Time Travel' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/the-s-classes-that-i-raised.jpg',
    },
    {
        id: 'nb:trash-of-the-counts-family',
        mal_id: 'nb:trash-of-the-counts-family',
        title: "Trash of the Count's Family",
        title_english: "Trash of the Count's Family",
        title_romaji: 'Baekjakgoui Mangnaniga Doeeotda',
        title_native: '백작가의 망나니가 되었다',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/trash-of-the-counts-family.jpg',
                large_image_url: 'https://novel-bin.com/files/image/trash-of-the-counts-family.jpg',
            },
        },
        score: 9.0,
        rank: 7,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:trash-of-the-counts-family',
        synopsis: 'When Kim Rok Soo opened his eyes, he was inside a novel titled The Birth of a Hero, inhabiting the body of Cale Henituse—the notorious trash noble destined to be beaten to a pulp by the protagonist. Determined to live a peaceful slacker life, his schemes somehow turn him into the continent’s hero.',
        author: 'Yoo Ryeo Han',
        genres: [
            { mal_id: 1, name: 'Fantasy' },
            { mal_id: 2, name: 'Transmigration' },
            { mal_id: 3, name: 'Comedy' },
            { mal_id: 4, name: 'Strategy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/trash-of-the-counts-family.jpg',
    },
    {
        id: 'nb:return-of-the-mount-hua-sect',
        mal_id: 'nb:return-of-the-mount-hua-sect',
        title: 'Return of the Mount Hua Sect',
        title_english: 'Return of the Mount Hua Sect',
        title_romaji: 'Hwasan Gwi-hwan',
        title_native: '화산귀환',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/return-of-the-mount-hua-sect.jpg',
                large_image_url: 'https://novel-bin.com/files/image/return-of-the-mount-hua-sect.jpg',
            },
        },
        score: 9.3,
        rank: 8,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:return-of-the-mount-hua-sect',
        synopsis: 'Chung Myung, the Plum Blossom Sword Saint of the Great Mount Hua Sect, slays the Heavenly Demon on the summit of Mount Hundred Thousand and takes his last breath. One hundred years later, he is reborn as a child only to discover the prestigious Mount Hua Sect has fallen into ruin.',
        author: 'Biga',
        genres: [
            { mal_id: 1, name: 'Murim' },
            { mal_id: 2, name: 'Martial Arts' },
            { mal_id: 3, name: 'Comedy' },
            { mal_id: 4, name: 'Reincarnation' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/return-of-the-mount-hua-sect.jpg',
    },
    {
        id: 'nb:overgeared',
        mal_id: 'nb:overgeared',
        title: 'Overgeared',
        title_english: 'Overgeared',
        title_romaji: 'Talsat',
        title_native: '템빨',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/overgeared.jpg',
                large_image_url: 'https://novel-bin.com/files/image/overgeared.jpg',
            },
        },
        score: 8.8,
        rank: 9,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:overgeared',
        synopsis: 'Shin Youngwoo has had an unfortunate life and is stuck carrying bricks in the VR game Satisfy. But luck finally turns when his character Grid discovers the legendary blacksmith class Book of Pagma.',
        author: 'Park Saenal',
        genres: [
            { mal_id: 1, name: 'VRMMO' },
            { mal_id: 2, name: 'Action' },
            { mal_id: 3, name: 'Crafting' },
            { mal_id: 4, name: 'Comedy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/overgeared.jpg',
    },
    {
        id: 'nb:the-greatest-estate-developer',
        mal_id: 'nb:the-greatest-estate-developer',
        title: 'The Greatest Estate Developer',
        title_english: 'The Greatest Estate Developer',
        title_romaji: 'Yeokdaegeup Yeongji Seolgyesa',
        title_native: '역대급 영지 설계사',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/the-greatest-estate-developer.jpg',
                large_image_url: 'https://novel-bin.com/files/image/the-greatest-estate-developer.jpg',
            },
        },
        score: 9.3,
        rank: 10,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:the-greatest-estate-developer',
        synopsis: 'Civil engineering student Kim Suho wakes up inside a fantasy novel as Lloyd Frontera, a useless, drunken noble heir whose family is burdened by astronomical debt. Armed with modern civil engineering knowledge, he rebuilds the estate and cons his way to prosperity.',
        author: 'BK_Moon',
        genres: [
            { mal_id: 1, name: 'Comedy' },
            { mal_id: 2, name: 'Kingdom Building' },
            { mal_id: 3, name: 'Fantasy' },
            { mal_id: 4, name: 'Isekai' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/the-greatest-estate-developer.jpg',
    },
    {
        id: 'nb:sss-class-suicide-hunter',
        mal_id: 'nb:sss-class-suicide-hunter',
        title: 'SSS-Class Suicide Hunter',
        title_english: 'SSS-Class Suicide Hunter',
        title_romaji: 'SSS-geup Jasalheonteo',
        title_native: 'SSS급 죽어야 사는 헌터',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/sss-class-suicide-hunter.jpg',
                large_image_url: 'https://novel-bin.com/files/image/sss-class-suicide-hunter.jpg',
            },
        },
        score: 9.2,
        rank: 11,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:sss-class-suicide-hunter',
        synopsis: 'Kim Gong-ja lives in misery at the bottom of the Babel Tower until he awakens an S+ skill that allows him to copy the ability of anyone who kills him, combined with a rewind death skill.',
        author: 'Shin Noah',
        genres: [
            { mal_id: 1, name: 'Tower' },
            { mal_id: 2, name: 'Time Loop' },
            { mal_id: 3, name: 'Action' },
            { mal_id: 4, name: 'Psychological' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/sss-class-suicide-hunter.jpg',
    },
    {
        id: 'nb:damn-reincarnation',
        mal_id: 'nb:damn-reincarnation',
        title: 'Damn Reincarnation',
        title_english: 'Damn Reincarnation',
        title_romaji: 'Billeomeogeul Hwansaeng',
        title_native: '빌어먹을 환생',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/damn-reincarnation.jpg',
                large_image_url: 'https://novel-bin.com/files/image/damn-reincarnation.jpg',
            },
        },
        score: 8.9,
        rank: 12,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'KR',
        source: 'novelbin',
        scraper_id: 'nb:damn-reincarnation',
        synopsis: 'The mercenary Hamel set out with his heroic companions to defeat the Great Demon Kings, dying to protect his friend Vermouth. Reincarnated 300 years later into the prestigious Lionheart clan as Vermouth’s descendant, his new quest begins.',
        author: 'Mogma',
        genres: [
            { mal_id: 1, name: 'Action' },
            { mal_id: 2, name: 'Reincarnation' },
            { mal_id: 3, name: 'Fantasy' },
            { mal_id: 4, name: 'Magic' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/damn-reincarnation.jpg',
    },
];

export const POPULAR_CHINESE_NOVELS: LightNovel[] = [
    {
        id: 'nb:lord-of-the-mysteries',
        mal_id: 'nb:lord-of-the-mysteries',
        title: 'Lord of the Mysteries',
        title_english: 'Lord of the Mysteries',
        title_romaji: 'Guimi Zhi Zhu',
        title_native: '诡秘之主',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/lord-of-the-mysteries.jpg',
                large_image_url: 'https://novel-bin.com/files/image/lord-of-the-mysteries.jpg',
            },
        },
        score: 9.6,
        rank: 1,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:lord-of-the-mysteries',
        synopsis: 'With the rising tide of steam power and machinery, who can come close to becoming a Beyonder? Shrouded in the fog of history and darkness, Zhou Mingrui awakens in the body of Klein Moretti in an alternate Victorian world intertwined with eldritch horrors, tarot divinations, and potion sequences.',
        author: 'Cuttlefish That Loves Diving',
        genres: [
            { mal_id: 1, name: 'Mystery' },
            { mal_id: 2, name: 'Steampunk' },
            { mal_id: 3, name: 'Lovecraftian' },
            { mal_id: 4, name: 'Fantasy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/lord-of-the-mysteries.jpg',
    },
    {
        id: 'nb:reverend-insanity-2',
        mal_id: 'nb:reverend-insanity-2',
        title: 'Reverend Insanity',
        title_english: 'Reverend Insanity',
        title_romaji: 'Gu Zhen Ren',
        title_native: '蛊真人',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/reverend-insanity-2.jpg',
                large_image_url: 'https://novel-bin.com/files/image/reverend-insanity-2.jpg',
            },
        },
        score: 9.5,
        rank: 2,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:reverend-insanity-2',
        synopsis: 'Fang Yuan reincarnates 500 years into the past with the legendary Spring Autumn Cicada. Utilizing his vast past-life wisdom, tactical ruthlessness, and mastery over Gu worms, he walks the solitary path toward true eternal life.',
        author: 'Gu Zhen Ren',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Cultivation' },
            { mal_id: 3, name: 'Dark' },
            { mal_id: 4, name: 'Strategy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/reverend-insanity-2.jpg',
    },
    {
        id: 'nb:martial-peak-2',
        mal_id: 'nb:martial-peak-2',
        title: 'Martial Peak',
        title_english: 'Martial Peak',
        title_romaji: 'Wu Lian Feng Feng',
        title_native: '武炼巅峰',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/martial-peak-2.jpg',
                large_image_url: 'https://novel-bin.com/files/image/martial-peak-2.jpg',
            },
        },
        score: 8.8,
        rank: 3,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:martial-peak-2',
        synopsis: 'The journey to the martial peak is a lonely, solitary and long one. In the face of adversity, you must survive and remain unyielding. Yang Kai, a trial disciple of High Heaven Pavilion, obtains a Black Book that alters his martial destiny forever.',
        author: 'Momo',
        genres: [
            { mal_id: 1, name: 'Martial Arts' },
            { mal_id: 2, name: 'Cultivation' },
            { mal_id: 3, name: 'Action' },
            { mal_id: 4, name: 'Harem' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/martial-peak-2.jpg',
    },
    {
        id: 'nb:the-founder-of-diabolism',
        mal_id: 'nb:the-founder-of-diabolism',
        title: 'Grandmaster of Demonic Cultivation',
        title_english: 'Grandmaster of Demonic Cultivation (Mo Dao Zu Shi)',
        title_romaji: 'Mo Dao Zu Shi',
        title_native: '魔道祖师',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/the-founder-of-diabolism.jpg',
                large_image_url: 'https://novel-bin.com/files/image/the-founder-of-diabolism.jpg',
            },
        },
        score: 9.3,
        rank: 4,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:the-founder-of-diabolism',
        synopsis: 'As the grandmaster who founded the Demonic Sect, Wei Wuxian roamed the world in his wanton ways, hated by millions for the chaos he created. Reincarnating thirteen years later into the body of a lunatic, he reunites with his old acquaintance Lan Wangji to unravel hidden conspiracies.',
        author: 'Mo Xiang Tong Xiu',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Supernatural' },
            { mal_id: 3, name: 'Mystery' },
            { mal_id: 4, name: 'Historical' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/the-founder-of-diabolism.jpg',
    },
    {
        id: 'nb:heaven-officials-blessing',
        mal_id: 'nb:heaven-officials-blessing',
        title: "Heaven Official's Blessing",
        title_english: "Heaven Official's Blessing (Tian Guan Ci Fu)",
        title_romaji: 'Tian Guan Ci Fu',
        title_native: '天官赐福',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/heaven-officials-blessing.jpg',
                large_image_url: 'https://novel-bin.com/files/image/heaven-officials-blessing.jpg',
            },
        },
        score: 9.4,
        rank: 5,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:heaven-officials-blessing',
        synopsis: 'Eight hundred years ago, Xie Lian was the Crown Prince of the Xianle kingdom, beloved by his citizens and ascendant to heaven. Banished twice and reduced to collecting scrap, he ascends for the third time and meets Hua Cheng, the fearsome Ghost King of the realm.',
        author: 'Mo Xiang Tong Xiu',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Mythology' },
            { mal_id: 3, name: 'Romance' },
            { mal_id: 4, name: 'Drama' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/heaven-officials-blessing.jpg',
    },
    {
        id: 'nb:coiling-dragon',
        mal_id: 'nb:coiling-dragon',
        title: 'Coiling Dragon',
        title_english: 'Coiling Dragon',
        title_romaji: 'Pan Long',
        title_native: '盘龙',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/coiling-dragon.jpg',
                large_image_url: 'https://novel-bin.com/files/image/coiling-dragon.jpg',
            },
        },
        score: 8.9,
        rank: 6,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:coiling-dragon',
        synopsis: 'In the Yulan continent, magical beasts roam and the strong reign supreme. Linley Baruch, a young noble of the declining Dragonblood Warrior clan, discovers the ancient Coiling Dragon ring and commences his epic climb toward divine godhood.',
        author: 'I Eat Tomatoes',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Action' },
            { mal_id: 3, name: 'Adventure' },
            { mal_id: 4, name: 'High Fantasy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/coiling-dragon.jpg',
    },
    {
        id: 'nb:battle-through-the-heavens',
        mal_id: 'nb:battle-through-the-heavens',
        title: 'Battle Through the Heavens',
        title_english: 'Battle Through the Heavens',
        title_romaji: 'Doupo Cangqiong',
        title_native: '斗破苍穹',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/battle-through-the-heavens.jpg',
                large_image_url: 'https://novel-bin.com/files/image/battle-through-the-heavens.jpg',
            },
        },
        score: 8.7,
        rank: 7,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:battle-through-the-heavens',
        synopsis: 'In a land where Dou Qi reigns supreme, young genius Xiao Yan mysteriously loses all his powers and faces ridicule from his clan. Everything shifts when he awakens the spirit of master Yao Lao inside his mother’s heirloom ring.',
        author: 'Heavenly Silkworm Potato',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Alchemy' },
            { mal_id: 3, name: 'Action' },
            { mal_id: 4, name: 'Adventure' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/battle-through-the-heavens.jpg',
    },
    {
        id: 'nb:renegade-immortal',
        mal_id: 'nb:renegade-immortal',
        title: 'Renegade Immortal',
        title_english: 'Renegade Immortal (Xian Ni)',
        title_romaji: 'Xian Ni',
        title_native: '仙逆',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/renegade-immortal.jpg',
                large_image_url: 'https://novel-bin.com/files/image/renegade-immortal.jpg',
            },
        },
        score: 9.1,
        rank: 8,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:renegade-immortal',
        synopsis: 'Wang Lin is a mediocre-talented boy whose life transforms after finding the mysterious Heavenly Defying Bead. Armed with sheer tenacity, he steps onto the brutal path of cultivation to protect his family.',
        author: 'Er Gen',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Cultivation' },
            { mal_id: 3, name: 'Tragedy' },
            { mal_id: 4, name: 'Martial Arts' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/renegade-immortal.jpg',
    },
    {
        id: 'nb:the-kings-avatar',
        mal_id: 'nb:the-kings-avatar',
        title: "The King's Avatar",
        title_english: "The King's Avatar (Quan Zhi Gao Shou)",
        title_romaji: 'Quan Zhi Gao Shou',
        title_native: '全职高手',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/the-kings-avatar.jpg',
                large_image_url: 'https://novel-bin.com/files/image/the-kings-avatar.jpg',
            },
        },
        score: 9.0,
        rank: 9,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:the-kings-avatar',
        synopsis: 'In the online game Glory, Ye Xiu is a legendary top-tier pro player regarded as the Battle God. Expelled from his team, he works as an internet cafe manager and makes a triumphant return in Glory’s newly launched 10th server with the unspecialized character Lord Grim.',
        author: 'Butterfly Blue',
        genres: [
            { mal_id: 1, name: 'Gaming' },
            { mal_id: 2, name: 'Esports' },
            { mal_id: 3, name: 'Action' },
            { mal_id: 4, name: 'Comedy' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/the-kings-avatar.jpg',
    },
    {
        id: 'nb:release-that-witch',
        mal_id: 'nb:release-that-witch',
        title: 'Release That Witch',
        title_english: 'Release That Witch',
        title_romaji: 'Fang Kai Na Ge Nvwu',
        title_native: '放开那个女巫',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/release-that-witch.jpg',
                large_image_url: 'https://novel-bin.com/files/image/release-that-witch.jpg',
            },
        },
        score: 8.9,
        rank: 10,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:release-that-witch',
        synopsis: 'Modern mechanical engineer Cheng Yan is transmigrated into Prince Roland in a medieval European-style world. Saving Anna from being burned as a witch, he harnesses the magical powers of witches as industrial machinery to spark an industrial revolution.',
        author: 'Er Mu',
        genres: [
            { mal_id: 1, name: 'Kingdom Building' },
            { mal_id: 2, name: 'Science' },
            { mal_id: 3, name: 'Fantasy' },
            { mal_id: 4, name: 'Transmigration' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/release-that-witch.jpg',
    },
    {
        id: 'nb:a-will-eternal',
        mal_id: 'nb:a-will-eternal',
        title: 'A Will Eternal',
        title_english: 'A Will Eternal (Yi Nian Yong Heng)',
        title_romaji: 'Yi Nian Yong Heng',
        title_native: '一念永恒',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/a-will-eternal.jpg',
                large_image_url: 'https://novel-bin.com/files/image/a-will-eternal.jpg',
            },
        },
        score: 9.0,
        rank: 11,
        status: 'Completed',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:a-will-eternal',
        synopsis: 'Bai Xiaochun is an endearing youngster who is driven by one singular fear: he is terrified of dying. His quest for immortality begins with a single stick of incense, bringing hilarious chaos to the Spirit Stream Sect.',
        author: 'Er Gen',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Comedy' },
            { mal_id: 3, name: 'Cultivation' },
            { mal_id: 4, name: 'Action' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/a-will-eternal.jpg',
    },
    {
        id: 'nb:tales-of-demons-and-gods',
        mal_id: 'nb:tales-of-demons-and-gods',
        title: 'Tales of Demons and Gods',
        title_english: 'Tales of Demons and Gods (Yao Shen Ji)',
        title_romaji: 'Yao Shen Ji',
        title_native: '妖神记',
        images: {
            jpg: {
                image_url: 'https://novel-bin.com/files/image/tales-of-demons-and-gods.jpg',
                large_image_url: 'https://novel-bin.com/files/image/tales-of-demons-and-gods.jpg',
            },
        },
        score: 8.7,
        rank: 12,
        status: 'Ongoing',
        type: 'NOVEL',
        countryOfOrigin: 'CN',
        source: 'novelbin',
        scraper_id: 'nb:tales-of-demons-and-gods',
        synopsis: 'Nie Li, the strongest Demon Spiritist who fell in battle against the Sage Emperor, reincarnates into his 13-year-old self. Armed with knowledge of the future, he trains to protect Glory City from the upcoming demonic beast stampede.',
        author: 'Mad Snail',
        genres: [
            { mal_id: 1, name: 'Xianxia' },
            { mal_id: 2, name: 'Reincarnation' },
            { mal_id: 3, name: 'Action' },
            { mal_id: 4, name: 'Magic' },
        ],
        bannerImage: 'https://novel-bin.com/files/image/tales-of-demons-and-gods.jpg',
    },
];
